### ISSUE TITLE
how to support int16 image

### ISSUE THREAD

**Issue by Achuan-2** [rharkes/Fast_Tiff_Write#3]
My data is int16 tif

**Comment by rharkes** [comment]
Ah, that should not be very difficult.

[The sampleformat](https://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html) allows for it. 

I can add it as a case here:
https://github.com/rharkes/Fast_Tiff_Write/blob/master/Fast_Tiff_Write.m#L94

**Comment by Achuan-2** [comment]
so int16 data should be `bps = 2;sf=2;` , am I right?

**Comment by rharkes** [comment]
Exactly. If you would make a pull request that would be great. Maybe you could add `int8` as well.

**Comment by Achuan-2** [comment]
thanks. I have made a pull request: https://github.com/rharkes/Fast_Tiff_Write/pull/5
