### ISSUE TITLE
how to support custom tiff tag

### ISSUE THREAD

**Issue by Achuan-2** [rharkes/Fast_Tiff_Write#4]
like XResolution, YResolution, and ResolutionUnit

**Comment by rharkes** [comment]
All three are written. You can give the pixelsize in pix/cm when creating the object.

What would you like to do with these tags?

**Comment by Achuan-2** [comment]
I have a tif, which 512 * 512 pixels, representing 285um x 285um. I hope to use Matlab to process the image and use your function to save the image while retaining resolution information. I do know how to modify code to meet my needs? If you could help me, I would be very grateful.
[file_00001_ch1.zip](https://github.com/rharkes/Fast_Tiff_Write/files/14482663/file_00001_ch1.zip)
![Clip_2024-03-04_22-16-29](https://github.com/rharkes/Fast_Tiff_Write/assets/60436214/2eace140-24c1-49da-8729-3485d1211c4b)

**Comment by rharkes** [comment]
Yes, that would be possible with the current code, no need for changes. You would need to calculate how many pixels there would be in a cm. That can be done like this:
```
pixelsize = 285/512 ; % um/pix
pixelsize = 1/pixelsize; % pix/um
pixelsize = pixelsize*1E4; % pix/cm (there are 1E4 um in a cm)
obj = Fast_Tiff_Write(myfile.tif,pixelsize);
```
Let me know if this works for you.

**Comment by Achuan-2** [comment]
thanks a lot. It works!
