### ISSUE TITLE
XResolution and YResolution could be set separately

### ISSUE THREAD

**Issue by Achuan-2** [rharkes/Fast_Tiff_Write#6]
Consider that the aspect ratio of the image is not 1:1

**Comment by Achuan-2** [comment]
* [[✨XResolution and YResolution could be set separately · Achuan-2/Fast_Tiff_Write@04a481a (github.com)](https://github.com/Achuan-2/Fast_Tiff_Write/commit/04a481a1e65f1a3010d6defc64d80cea425667fd)](https://github.com/Achuan-2/Fast_Tiff_Write/commit/04a481a1e65f1a3010d6defc64d80cea425667fd)
* [[✨XResolution and YResolution could be set separately · Achuan-2/Fast_Tiff_Write@e04fb54 (github.com)](https://github.com/Achuan-2/Fast_Tiff_Write/commit/e04fb54bcf4f2a38bca2c7f0c87e265cad4a58ba)](https://github.com/Achuan-2/Fast_Tiff_Write/commit/e04fb54bcf4f2a38bca2c7f0c87e265cad4a58ba)

**Comment by rharkes** [comment]
Hi @Achuan-2 ,
Thanks for the suggestion, but I don't think this is a feature that will be used often. It mostly will cause confusion I think. It is a feature of the tiff format that you can work with pixels that have a different size in x and y. But have you ever encountered an image where the pixels are of a different size in x and y?

**Comment by Achuan-2** [comment]
Yes, our laboratory have developed some custom microscopes, so some images may have different aspect ratios. Although, most of the time, the images are indeed square in shape.

**Comment by rharkes** [comment]
Can you share such a picture?
Because I fear you confuse the image aspect ratio (for example 256x512 pixels) with pixels that have different size in x and y (for example 2um in x 4 um in y).

**Comment by Achuan-2** [comment]
oh, sorry. I got confused. You are right.
