### ISSUE TITLE
In Matlab 2023b, Fast_Tiff_Write vs Tifflib

### ISSUE THREAD

**Issue by Achuan-2** [rharkes/Fast_Tiff_Write#7]
Using Fast_Tiff_Write to save large TIFF files takes approximately half the time compared to saving with the Tiff library. The time difference between the two is not more than ten times greater than stated in Readme.
only change the tags in code.
```matlab
tf.setTag('Photometric',Tiff.Photometric.MinIsBlack);
tf.setTag('Compression',Tiff.Compression.None);
tf.setTag('BitsPerSample',16);
tf.setTag('SamplesPerPixel',1);
tf.setTag('SampleFormat',Tiff.SampleFormat.UInt);
tf.setTag('ImageLength',size(IM,1));
tf.setTag('ImageWidth',size(IM,2));
tf.setTag('ResolutionUnit',3);
tf.setTag('PlanarConfiguration',Tiff.PlanarConfiguration.Chunky);
```
![image](https://github.com/rharkes/Fast_Tiff_Write/assets/60436214/d5f27f4c-578b-43e9-81b2-354f9e03e648)

My Computer is Thinkbook 16+ 2023,CPU is AMD R7480H, GPU is GTX 4050

**Comment by rharkes** [comment]
Thank you for pointing this out. When I wrote it, it was 10x as fast. However I am glad to see that the tifflib integration in Matlab has improved. I'll update the readme.

**Comment by Achuan-2** [comment]
OK, thanks for your code.
